In [5]:
# Imports all the library
import sklearn.linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf


# Pandas print options seting
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


# Link to the and named file
file = './birthweight_low (1).xlsx'


# reading the file into Python
data = pd.read_excel(io = file,
                       header = 0)


# outputting the first ten rows of the dataset
data.head(n=5)

   mage  meduc  monpre  npvis  fage  feduc  omaps  fmaps  cigs  drink  male  mwhte  mblck  moth  fwhte  fblck  foth  bwght
0    23   11.0       4   11.0    46   12.0      8      9    13      4     0      0      0     1      0      1     0   3600
1    23   16.0       3   10.0    50   12.0      3      8     1      1     1      0      1     0      0      1     0   3912
2    24   16.0       1   12.0    26   16.0      6      9    21      4     0      0      0     1      0      0     1   3090
3    25   14.0       3   12.0    33   12.0      9      9    12      7     1      0      1     0      0      1     0   3370
4    25   12.0       2    8.0    32   12.0      9      9     4      3     0      0      1     0      0      1     0   3827

In [6]:
# using .shape to check the number of ROWS and COLUMNS
print(f"""shape: {data.shape}""")

# checking information about each variable
print(f"""{data.info()}""")

shape: (352, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mage    352 non-null    int64
 1   meduc   349 non-null    float64
 2   monpre  352 non-null    int64
 3   npvis   349 non-null    float64
 4   fage    352 non-null    int64
 5   feduc   345 non-null    float64
 6   omaps   352 non-null    int64
 7   fmaps   352 non-null    int64
 8   cigs    352 non-null    int64
 9   drink   352 non-null    int64
 10  male    352 non-null    int64
 11  mwhte   352 non-null    int64
 12  mblck   352 non-null    int64
 13  moth    352 non-null    int64
 14  fwhte   352 non-null    int64
 15  fblck   352 non-null    int64
 16  foth    352 non-null    int64
 17  bwght   352 non-null    int64
dtypes: float64(3), int64(15)
memory usage: 49.6 KB
None

In [7]:
## Preparing R Square

# Initialize stats model
model = smf.ols(formula = "bwght ~ mage * fage + cigs * drink", data = data)

result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  bwght   R-squared:                       0.713
Model:                            OLS   Adj. R-squared:                  0.708
Method:                 Least Squares   F-statistic:                     142.8
Date:                Tue, 15 Mar 2022   Prob (F-statistic):           2.53e-90
Time:                        00:08:53   Log-Likelihood:                -2613.2
No. Observations:                 352   AIC:                             5240.
Df Residuals:                     345   BIC:                             5267.
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   2237.5552    349.007      6.411      0.000    1551.106    2924.004
mage          42.0784      9.503      4.428      0.000      23.388      60.769
fage          36.8948      8.337      4.425      0.000      20.496      53.293
mage:fage     -1.0779      0.192     -5.600      0.000      -1.456      -0.699
cigs          18.1728      6.058      3.000      0.003       6.257      30.088
drink         21.5268     12.514      1.720      0.086      -3.087      46.141
cigs:drink    -8.6671      0.886     -9.787      0.000     -10.409      -6.925
==============================================================================
Omnibus:                       51.061   Durbin-Watson:                   1.433
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              122.082
Skew:                           0.720   Prob(JB):                     3.09e-27
Kurtosis:                       5.500   Cond. No.                     3.04e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.04e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [8]:
## Prepare data for training

# Preparing target 
target = data.loc[ : , ['bwght']]

# Preparing training data

data['mf_age'] = data['mage'] * data['fage']
data['s+d'] = data['cigs'] * data['drink']

# Selecting columns to train model with for training data
t_data = data.loc[ : , ['mage' ,'fage', 'cigs', 'drink', 'mf_age', 's+d'] ]


# Decouple training and test set
x_train, x_test, y_train, y_test = train_test_split(
            t_data,
            target,
            test_size = 0.25,
            random_state = 219)

# Print shape of x_train and y_train
print(f"""
Training set
x_train: {x_train.shape}
y_train: {y_train.shape}
""")

Training set
x_train: (264, 6)
y_train: (264, 1)

In [9]:
# Neighbors regressor 

# Prepare namaed data
data = pd.DataFrame(birth).copy(True)
data = data.fillna(0)

# Target
target = data.loc[ : , ['bwght']]

# Selecting only these columns increases gap slightly
# t_data = data.loc[ : , ['mage' ,'fage', 'cigs', 'drink'] ]

# Remove target from data
t_data = data
t_data = t_data.drop(['bwght'], axis=1)

# Decouple training and test set
x_train, x_test, y_train, y_test = train_test_split(
            t_data,
            target,
            test_size = 0.25,
            random_state = 219)

#display(x_train)


# Neighbor 
knn_reg = KNeighborsRegressor(algorithm = 'auto',
                              n_neighbors = 16
                             )


# FITTING to the training data
knn_fit = knn_reg.fit(x_train, y_train)


# PREDICTING on new data
knn_reg_pred = knn_fit.predict(x_test)

# Score
print('KNN Training Score:', knn_reg.score(x_train, y_train).round(4))
print('KNN Testing Score :',  knn_reg.score(x_test, y_test).round(4))


# saving scoring data for future use
knn_reg_score_train = knn_reg.score(x_train, y_train).round(4)
knn_reg_score_test  = knn_reg.score(x_test, y_test).round(4)


# displaying and saving the gap between training and testing
print('KNN Train-Test Gap:', abs(knn_reg_score_train - knn_reg_score_test).round(4))
knn_reg_test_gap = abs(knn_reg_score_train - knn_reg_score_test).round(4)

KNN Training Score: 0.7087
KNN Testing Score : 0.6954
KNN Train-Test Gap: 0.0133

In [11]:
# Preparing data

# Prepare data
data = pd.DataFrame(birth).copy(True)
data = data.fillna(0)



# Target
target = data.loc[ : , ['bwght']]

# Convert to 1 dimension target for ARD
target = target.squeeze()
print(target.shape)

# Selecting only these columns increases gap slightly
#t_data = data.loc[ : , ['mage' ,'fage', 'cigs', 'drink'] ]

data['mf_age'] = data['mage'] * data['fage']
data['s+d'] = data['cigs'] * data['drink']

# Selecting columns to train model with for training data
t_data = data.loc[ : , ['mage' ,'fage', 'cigs', 'drink', 'mf_age', 's+d'] ]



# Remove target from data
t_data = data
t_data = t_data.drop(['bwght'], axis=1)

# Decouple training and test set
x_train, x_test, y_train, y_test = train_test_split(
            t_data,
            target,
            test_size = 0.25,
            random_state = 219)

(352,)

In [12]:
# Train with ARD

# INSTANTIATING a model object
ard_model = sklearn.linear_model.ARDRegression(normalize  = False)


# FITTING the training data
ard_fit = ard_model.fit(x_train, y_train)


# PREDICTING on new data
ard_pred = ard_fit.predict(x_test)


print('Training Score:', ard_model.score(x_train, y_train).round(4))
print('Testing Score :',  ard_model.score(x_test, y_test).round(4))


# saving scoring data for future use
ard_train_score = ard_model.score(x_train, y_train).round(4)
ard_test_score  = ard_model.score(x_test, y_test).round(4)


# displaying and saving the gap between training and testing
print('ARD Train-Test Gap :', abs(ard_train_score - ard_test_score).round(4))
ard_test_gap = abs(ard_train_score - ard_test_score).round(4)

Training Score: 0.7175
Testing Score : 0.6924
ARD Train-Test Gap : 0.0251